version: '3'
services:
 #Nginx-service
  webserver:
    restart: always
    container_name: webserver
    image: prabhat2020/myhtmlapp:1.0.0
    ports:
      - "8080:80"
# Mysql image
  db:
   image: mysql:latest
   container_name: MysqlDB
   restart: always
   ports:
     - "3306:3306"
   environment:
     MYSQL_DATABASE: webserverdb
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: webserverdb
     SERVICE_TAGS: dev
     SERVICE_NAME: mysql
